### ISSUE TITLE
IPLS bug using AE

### ISSUE THREAD

**Issue by mrcfon** [narykov/Stone-Soup#1]
IPLS breaks for not definite positive covariance matrix error using AE measurement model in scenarios with measurement gaps. The error happens at the second iteration of IPLS (the one after UKF smoother) because the results of UKF smoother are not good.

**Comment by mrcfon** [comment]
I tested the IPLS based on the UKF filter rather IPLF, but I got the same error just a few time steps later.

**Comment by mrcfon** [comment]
According to Angel:

- Setting the prior at time step k=0, predict to k=1, get the first measurement and we update --> **should work**.

- Setting the prior and the first measurement both at k=0 --> **may create problems**, unless we do the extra prediction (ask Ben).

**Comment by mrcfon** [comment]
The same error was encountered using AER.

**Comment by mrcfon** [comment]
Update: the error (Matrix is not positive definite) occurs using any measurement model (CartesianToElevationBearingRangeRate, CartesianToMonostatic, CartesianToTelescope) with measurement gaps.

**Comment by mrcfon** [comment]
I'm trying to understand why the IPLF and IPLS return weird results if I set q_value = 5e-9 (it was previously set to q = 0.02).
I tested a few things:
1. The code returns the same results using the last version of Stone Soup (v 1.2+) or the one released in December.
2. I plotted the angles and they look fine. Note that bearing is \in [0,90] degrees in the simulation. I also tried to add a small offset to elevation to ensure it's always positive, but I got similar results. 
![elevation_bearing_deg_in_GODOT_1man](https://github.com/narykov/Stone-Soup/assets/156119965/33cf9a9e-04b1-4138-950b-add7d39af788)

While I originally tested the scenario with a measurement gap, I simplified it assuming we receive a measurement at each time step. See the scenario below.
![scenario_no_gap](https://github.com/narykov/Stone-Soup/assets/156119965/99256a37-ad58-4dc7-9d4d-31058f13eede)

This is the result I get setting the number of iterations for IPLF to 5:
![res_IPLF_5iter](https://github.com/narykov/Stone-Soup/assets/156119965/d2acd820-d7f2-4eff-82dc-791a43c4df27)

If I set the number of iterations for IPLF to 1 I get:
![res_IPLF_1iter](https://github.com/narykov/Stone-Soup/assets/156119965/106b3844-1a50-447f-9182-67f2a28c71ab)
This is the Euclidian distance of the algorithms in this case
![perf_IPLF_1iter](https://github.com/narykov/Stone-Soup/assets/156119965/20473d16-edd6-48ad-971b-a9e25f26502a)

Iterating IPLF 5 times instead of just once brings down the error of IPLS from 1e15 to 1e8.
I'll try to see what happens if I replace IPLF with one iteration with UFK from the Stone Soup library.
Any other suggestions @narykov?

**Comment by mrcfon** [comment]
I’m trying to understand why the second iteration of IPLS doesn’t run on the TLE scenarios with measurement gaps. It seems that the UKF smoother used in the first iteration of IPLS returns “bad“ covariance matrices, so the proper IPLS breaks due to a incorrect input. Here are some facts:

UKF and IPLF with one iterarions are equivalent.

Using UKF, the UKF smoother returns non positive definite covariance matrices at the end of the measurement gaps. The eigenvalues may look like:  [-6.47835139e+08,  1.55118343e+08, -1.87036495e+08,  9.46675460e-01, 8.19938443e-01,  8.71217637e-01].

The number of non positive definite covariance matrices at the end of the measurement gaps depends on q_value.

The issues occurs regardless of whether a manoeuvre is present in the simulation, even if a manoeuvre makes the problem more evident/likely.

IPLF with max_n_iter > 1 increases the chanses to have the UKF smoother returning non positive definite covariance matrices.

Points 2 and 4 are concerning. In point 2, the only non-Stone Soup component in the process chain is the transition model (based on GODOT), and the ground truth generated with GODOT. UKF has force_symmetric_covariance=True.

In point 4, symmetry of the Omega returned by the SLR function is enforced.

The next step would be to test the UKF smoother in a linear scenario (without GODOT) with measurement gaps. Any other suggestions?

**Comment by mrcfon** [comment]
IPLS may return errors at the second iteration (the first after UKF smoothing) even in a scenario with no measurement gaps. Note there was a manoeuvre in this scenario. Here is the error:
`IPLS iteration 1 out of 2
IPLS iteration 2 out of 2
Traceback (most recent call last):
  File "/home/mrcfon/workspace/space_manoeuvres/stonesoup/space_manoeuvres/STT_noDA_GODOT_TLEs.py", line 201, in <module>
    main()
  File "/home/mrcfon/workspace/space_manoeuvres/stonesoup/space_manoeuvres/STT_noDA_GODOT_TLEs.py", line 163, in main
    track_ipls = IPLSKalmanSmoother(transition_model=transition_model, n_iterations=n_iterations_ipls).smooth(
  File "/home/mrcfon/workspace/space_manoeuvres/stonesoup/robusstod/stonesoup/smoother.py", line 137, in smooth
    smoothed_track = KalmanSmoother(transition_model=None).smooth(track_forward)  # <- this triggers UKF??
  File "/home/mrcfon/workspace/space_manoeuvres/stonesoup/smoother/kalman.py", line 183, in smooth
    ksmooth_gain = self._smooth_gain(
  File "/home/mrcfon/workspace/space_manoeuvres/stonesoup/smoother/kalman.py", line 150, in _smooth_gain
    @ np.linalg.inv(prediction.covar)
  File "/home/mrcfon/workspace/space_manoeuvres/myenv/lib/python3.10/site-packages/numpy/linalg/linalg.py", line 561, in inv
    ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)
  File "/home/mrcfon/workspace/space_manoeuvres/myenv/lib/python3.10/site-packages/numpy/linalg/linalg.py", line 112, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
numpy.linalg.LinAlgError: Singular matrix`

**Comment by narykov** [comment]
Thanks for the update. Do you encounter this error despite changing how the measurement prediction works in the update step?
